####################################################
# By default, use the current production image hosted
# in the GitLab repo's container registry.
# This image can be overriden by job-specific images.
####################################################
image: $CI_REGISTRY_IMAGE:prd

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - .sf/
    - .sfdx/

stages: 
  - build
  - backfill
  - validate
  - destroy
  - deploy

variables:
  DEPLOY_TIMEOUT: 240
  DEPLOY_LOG: deploy_log.txt
  DEPLOY_PACKAGE: package.xml
  # Update webhook URL here for your slack channel
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/

####################################################
# Build a Docker image for the org.
####################################################
build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind  
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME == 'dev' || $CI_COMMIT_REF_NAME == 'fqa'
      changes:
        - Dockerfile
      when: always
  allow_failure: false
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_HOST: tcp://docker:2376 #Necessary for k8s
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  # wait until docker in docker service is ready
  before_script:
    - until docker info; do sleep 1; done
  script:
    - if [ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]; then IMAGE_TAG=$CI_REGISTRY_IMAGE:prd; fi
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags: 
    - aws,prd,us-west-2

####################################################
# Push production commits back to sandbox branches.
# This will skip CI pipelines when pushing to GitLab.
####################################################
prodBackfill:
  stage: backfill
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'push'
      when: always
    - when: never
  allow_failure: true
  script:
    - source ./scripts/bash/merge_main_into_sbx.sh
  tags: 
    - aws,prd,us-west-2

#####################################################
# Authenticate to a Salesforce org.
####################################################
.authenticate:
  before_script:
    - echo y | sf plugins:install sfdx-git-delta
    - python3 ./scripts/python/create_deploy_package.py -f $BEFORE_SHA -t $CI_COMMIT_SHA -o $DEPLOY_PACKAGE -m "$COMMIT_MSG"
    - source_folder=$(python3 ./scripts/python/check_package_dir.py)
    - python3 ./scripts/python/authenticate_sf.py --alias $AUTH_ALIAS --url $AUTH_URL
    - testclasses=$(python3 ./scripts/python/apex_tests.py --tests "$COMMIT_MSG" --manifest $DEPLOY_PACKAGE)

####################################################
# Validate metadata in a Salesforce org.
####################################################
.validate-metadata:
  extends: .authenticate
  cache:
    key: ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    paths:
      - .sf/
      - .sfdx/
  script:
    - python3 ./scripts/python/deploy_metadata_sf.py --tests "$testclasses" --manifest $DEPLOY_PACKAGE --wait $DEPLOY_TIMEOUT --environment $CI_ENVIRONMENT_URL --log $DEPLOY_LOG --validate --pipeline $CI_PIPELINE_SOURCE | tee -a $DEPLOY_LOG
  after_script:
    - python3 ./scripts/python/deploy_slack_status.py --status "$CI_JOB_STATUS" --user "$GITLAB_USER_NAME" --job "$CI_JOB_URL" --project "$CI_PROJECT_URL" --commit "$CI_COMMIT_SHA" --environment "$CI_ENVIRONMENT_NAME" --webhook "$SLACK_WEBHOOK_URL"
    - rm $DEPLOY_PACKAGE
    - rm $DEPLOY_LOG

####################################################
# Deploy metadata into a Salesforce org.
####################################################
.deploy-metadata:
  extends: .authenticate
  script:
    # full-deploy if deploying non-apex
    # validate and quick-deploy if deploying apex
    - if [ "$testclasses" == "not a test" ];
      then python3 ./scripts/python/deploy_metadata_sf.py --tests "$testclasses" --manifest $DEPLOY_PACKAGE --wait $DEPLOY_TIMEOUT --environment $CI_ENVIRONMENT_URL --log $DEPLOY_LOG  | tee -a $DEPLOY_LOG;
      else python3 ./scripts/python/deploy_metadata_sf.py --tests "$testclasses" --manifest $DEPLOY_PACKAGE --wait $DEPLOY_TIMEOUT --environment $CI_ENVIRONMENT_URL --log $DEPLOY_LOG --validate | tee -a $DEPLOY_LOG;
      fi
  after_script:
    - python3 ./scripts/python/deploy_slack_status.py --status "$CI_JOB_STATUS" --user "$GITLAB_USER_NAME" --job "$CI_JOB_URL" --project "$CI_PROJECT_URL" --commit "$CI_COMMIT_SHA" --environment "$CI_ENVIRONMENT_NAME" --webhook "$SLACK_WEBHOOK_URL"
    - rm $DEPLOY_PACKAGE
    - rm $DEPLOY_LOG

####################################################
# Delete metadata in a Salesforce org.
####################################################
.delete-metadata:
  script:
    - echo y | sf plugins:install sfdx-git-delta
    - python3 ./scripts/python/authenticate_sf.py --alias $AUTH_ALIAS --url $AUTH_URL
    - python3 ./scripts/python/delete_metadata_sf.py --from_ref $BEFORE_SHA --to_ref $CI_COMMIT_SHA --wait $DEPLOY_TIMEOUT --environment $CI_ENVIRONMENT_URL --log $DEPLOY_LOG | tee -a $DEPLOY_LOG
  after_script:
    - rm $DEPLOY_LOG

####################################################
# Declare jobs for the sandbox org.
####################################################
validate:dev:
  image: $CI_REGISTRY_IMAGE:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  extends: .validate-metadata
  stage: validate
  resource_group: dev
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'dev' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'fqa' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev'
      when: manual
  allow_failure: false
  variables:
    AUTH_ALIAS: SANDBOX
    AUTH_URL: $SANDBOX_AUTH_URL
    # This will work in merge request pipelines and merged results pipelines
    BEFORE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    # If you are working on GitLab v16.6, switch to CI_MERGE_REQUEST_DESCRIPTION
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: validate-sandbox
    url: https://avalara--dev.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

deploy:dev:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  extends: .deploy-metadata
  stage: deploy
  resource_group: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $SANDBOX_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == 'dev'
      when: always
  allow_failure: false
  variables:
    AUTH_ALIAS: SANDBOX
    AUTH_URL: $SANDBOX_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: sandbox
    url: https://avalara--dev.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

destroy:dev:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  extends: .delete-metadata
  stage: destroy
  resource_group: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $SANDBOX_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == 'dev'
      when: always
  allow_failure: true
  variables:
    AUTH_ALIAS: SANDBOX
    AUTH_URL: $SANDBOX_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
  environment:
    name: sandbox
    url: https://avalara--dev.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

####################################################
# Declare jobs for the fqa org.
####################################################
validate:fqa:
  image: $CI_REGISTRY_IMAGE:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  extends: .validate-metadata
  stage: validate
  resource_group: fqa
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'dev' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'fqa' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'fqa'
      when: manual
  allow_failure: false
  variables:
    AUTH_ALIAS: FQA
    AUTH_URL: $FQA_AUTH_URL
    # This will work in merge request pipelines and merged results pipelines
    BEFORE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    # If you are working on GitLab v16.6, switch to CI_MERGE_REQUEST_DESCRIPTION
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: validate-fqa
    url: https://avalara--fqa.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

deploy:fqa:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  extends: .deploy-metadata
  stage: deploy
  resource_group: fqa
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $FQA_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == 'fqa'
      when: always
  allow_failure: false
  variables:
    AUTH_ALIAS: FQA
    AUTH_URL: $FQA_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: fqa
    url: https://avalara--fqa.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

destroy:fqa:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  extends: .delete-metadata
  stage: destroy
  resource_group: fqa
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $FQA_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == 'fqa'
      when: always
  allow_failure: true
  variables:
    AUTH_ALIAS: FQA
    AUTH_URL: $FQA_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
  environment:
    name: fqa
    url: https://avalara--fqa.sandbox.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

####################################################
# Declare jobs for the production org.
####################################################
validate:prd:
  extends: .validate-metadata
  stage: validate
  resource_group: prd
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'dev' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'fqa' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: false
  variables:
    AUTH_ALIAS: PRD
    AUTH_URL: $PRD_AUTH_URL
    # This will work in merge request pipelines and merged results pipelines
    BEFORE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    # If you are working on GitLab v16.6, switch to CI_MERGE_REQUEST_DESCRIPTION
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: validate-prod
    url: https://avalara.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

deploy:prd:
  extends: .deploy-metadata
  stage: deploy
  resource_group: prd
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $PRD_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
  allow_failure: false
  variables:
    AUTH_ALIAS: PRD
    AUTH_URL: $PRD_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
    COMMIT_MSG: $CI_COMMIT_MESSAGE
  environment:
    name: prd
    url: https://avalara.my.salesforce.com
  tags: 
    - aws,prd,us-west-2

destroy:prd:
  extends: .delete-metadata
  stage: destroy
  resource_group: prd
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $PRD_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
  allow_failure: true
  variables:
    AUTH_ALIAS: PRD
    AUTH_URL: $PRD_AUTH_URL
    BEFORE_SHA: $CI_COMMIT_BEFORE_SHA
  environment:
    name: prd
    url: https://avalara.my.salesforce.com
  tags: 
    - aws,prd,us-west-2
